language: objective-c
before_install:
  - export LANG=en_US.UTF-8
  - gem install cocoapods --no-rdoc
  - brew update
  - brew upgrade xctool
script:
  - xctool test -workspace GPSKit.xcworkspace -scheme GPSKit -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO